// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtjtWyGzfTzUCltVDhfhWBJHqTKZQBTao',
    appId: '1:122332632204:web:45a063f73d8da42e1e17a9',
    messagingSenderId: '122332632204',
    projectId: 'project-6187630146750465104',
    authDomain: 'project-6187630146750465104.firebaseapp.com',
    storageBucket: 'project-6187630146750465104.appspot.com',
    measurementId: 'G-9M7C86FSZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMb1KuC6rqk9-vmHTWUjV23E325PkkHO4',
    appId: '1:122332632204:android:38ab53353d3cd4621e17a9',
    messagingSenderId: '122332632204',
    projectId: 'project-6187630146750465104',
    storageBucket: 'project-6187630146750465104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3wFjLbWhvtTCLTtdEjgxz3lnt23S_Q7k',
    appId: '1:122332632204:ios:c663c846d347aaad1e17a9',
    messagingSenderId: '122332632204',
    projectId: 'project-6187630146750465104',
    storageBucket: 'project-6187630146750465104.appspot.com',
    iosClientId: '122332632204-kotcbf68efl6m31ik5q3ak6q67mb5475.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3wFjLbWhvtTCLTtdEjgxz3lnt23S_Q7k',
    appId: '1:122332632204:ios:c663c846d347aaad1e17a9',
    messagingSenderId: '122332632204',
    projectId: 'project-6187630146750465104',
    storageBucket: 'project-6187630146750465104.appspot.com',
    iosClientId: '122332632204-kotcbf68efl6m31ik5q3ak6q67mb5475.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab7',
  );
}
